global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '<email ID>'
  smtp_auth_username: '<email ID>'
  smtp_auth_password: '<app_password>'
  smtp_require_tls: true

route:
  receiver: 'gmail-receiver'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
- name: 'gmail-receiver'
  email_configs:
  - to: '<email ID>'
    send_resolved: true

templates:
- /etc/alertmanager/config/*.tmpl
